---
title: Www.Samprof.Com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: SamProf Blog
description: C# and JS Development
avatar: "/images/logo.jpg"
excerpt_separator: "<!--more-->"
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: samprof
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: www-samprof-com
google_analytics: UA-118748625-1
url: https://www.samprof.com
baseurl: 
permalink: "/:year/:month/:day/:slug"
version: v1.2.0
paginate: 5
paginate_path: "/blog/page:num/"
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
